terraform {
  required_providers {
    terratowns = {
      source = "local.providers/local/terratowns"
      version = "1.0.0"
    }
  }
  #   cloud {
  #     organization = "Vold-Industries"

  #     workspaces {
  #       name = "terra-house-1"
  #     }
  #   }
}
# provider "aws" {

# }

provider "terratowns" {
  endpoint  = var.terratowns_endpoint
  user_uuid = var.teacherseat_user_uuid
  token     = var.terratowns_access_token
}
module "terrahouse_aws" {
  source              = "./modules/terrahouse_aws"
  user_uuid           = var.teacherseat_user_uuid
  index_html_filepath = var.index_html_filepath
  error_html_filepath = var.error_html_filepath
  content_version     = var.content_version
  assets_path         = var.assets_path
}

resource "terratowns_home" "home" {
  name        = "Boardgames!"
  description = <<DESCRIPTION
Once upon a time in the land of Clueful Chess-opoly, players rolled dice made of laughter and moved their pieces, which were sentient marshmallows with top hats. 
The goal was to collect rainbow-colored houses made of cotton candy while avoiding the dreaded "Giggle-Goop" squares that turned your pawns into singing pineapples. 
The game's narrator was a quacking rubber duck named Sir Quacks-a-lot, who imparted wisdom in the form of interpretive dance. Players could also summon flying pancakes to disrupt their opponents, creating a delightful frenzy of syrupy chaos. 
The winner was crowned the Grand Fluffinator of Fanciful Frolics and got to wear the prestigious Sock-of-Silly Supremacy for a week. 
The end, or maybe just the beginning of the jello-filled jamboree!

*Generated by our friend and mentor, ChatGPT.
DESCRIPTION
  domain_name = module.terrahouse_aws.cloudfront_url
  town            = "missingo"
  content_version = 1
}