terraform {
  required_providers {
    terratowns = {
      source = "local.providers/local/terratowns"
      version = "1.0.0"
    }
  }
  cloud {
    organization = "Vold-Industries"

    workspaces {
      name = "terra-house-1"
    }
  }
}
# provider "aws" {

# }

provider "terratowns" {
  endpoint  = var.terratowns_endpoint
  user_uuid = var.teacherseat_user_uuid
  token     = var.terratowns_access_token
}

module "home_boardgame_hosting" {
  source = "./modules/terrahome_aws"
  user_uuid = var.teacherseat_user_uuid
  public_path = var.boardgames.public_path
  content_version = var.boardgames.content_version
}

resource "terratowns_home" "home" {
  name        = "Boardgames!"
  description = <<DESCRIPTION
Once upon a time in the land of Clueful Chess-opoly, players rolled dice made of laughter and moved their pieces, which were sentient marshmallows with top hats. 
The goal was to collect rainbow-colored houses made of cotton candy while avoiding the dreaded "Giggle-Goop" squares that turned your pawns into singing pineapples. 
The game's narrator was a quacking rubber duck named Sir Quacks-a-lot, who imparted wisdom in the form of interpretive dance. 
Players could also summon flying pancakes to disrupt their opponents, creating a delightful frenzy of syrupy chaos. 
The winner was crowned the Grand Fluffinator of Fanciful Frolics and got to wear the prestigious Sock-of-Silly Supremacy for a week. 
The end, or maybe just the beginning of the jello-filled jamboree!

*Generated by our friend and mentor, ChatGPT.
DESCRIPTION
  domain_name = module.home_boardgame_hosting.domain_name
  town = "gamers-grotto"
  # town = "missingo"
  content_version = var.boardgames.content_version
}
